# Google Cloud Build configuration for Elson Trading Platform
# Deploys to elsontb.com domain
steps:
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elson-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elson-backend:latest'
      - './backend'

  # Build Frontend Image  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elson-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elson-frontend:latest'
      - './frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/elson-backend:$COMMIT_SHA'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/elson-frontend:$COMMIT_SHA'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'elson-backend'
      - '--image=gcr.io/$PROJECT_ID/elson-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--concurrency=80'
      - '--timeout=300'
      - '--set-env-vars=ENVIRONMENT=production,PROJECT_ID=$PROJECT_ID'
      - '--quiet'
    waitFor: ['push-backend']

  # Deploy Frontend to Cloud Run  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'elson-frontend'
      - '--image=gcr.io/$PROJECT_ID/elson-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=5'
      - '--min-instances=1'
      - '--concurrency=100'
      - '--timeout=300'
      - '--quiet'
    waitFor: ['push-frontend']

# Specify the machine type for Cloud Build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: 1200s

# Substitutions for build variables
substitutions:
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: elson-trading-platform

images:
  - 'gcr.io/$PROJECT_ID/elson-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/elson-backend:latest'
  - 'gcr.io/$PROJECT_ID/elson-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/elson-frontend:latest'