"""Initial migration with enhanced models

Revision ID: 1167a82d321b
Revises: 
Create Date: 2025-07-13 18:18:31.265357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1167a82d321b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=100), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("is_tradable", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=True)
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("open_price", sa.Float(), nullable=False),
        sa.Column("high_price", sa.Float(), nullable=False),
        sa.Column("low_price", sa.Float(), nullable=False),
        sa.Column("close_price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.Column("previous_close", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("change_percentage", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timeframe", sa.String(length=20), nullable=False),
        sa.Column("is_adjusted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_symbol_timeframe_timestamp",
        "market_data",
        ["symbol", "timeframe", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_symbol_timestamp", "market_data", ["symbol", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_market_data_id"), "market_data", ["id"], unique=False)
    op.create_index(
        op.f("ix_market_data_symbol"), "market_data", ["symbol"], unique=False
    )
    op.create_table(
        "market_sentiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("content_summary", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("entities", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_symbol_timestamp_sentiment",
        "market_sentiment",
        ["symbol", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_sentiment_id"), "market_sentiment", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_market_sentiment_symbol"), "market_sentiment", ["symbol"], unique=False
    )
    op.create_table(
        "technical_indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("indicator_name", sa.String(length=50), nullable=False),
        sa.Column("timeframe", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("signal_line", sa.Float(), nullable=True),
        sa.Column("histogram", sa.Float(), nullable=True),
        sa.Column("upper_band", sa.Float(), nullable=True),
        sa.Column("lower_band", sa.Float(), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("signal", sa.String(length=20), nullable=True),
        sa.Column("strength", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_symbol_indicator_timestamp",
        "technical_indicators",
        ["symbol", "indicator_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_technical_indicators_id"), "technical_indicators", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_technical_indicators_symbol"),
        "technical_indicators",
        ["symbol"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("risk_tolerance", sa.String(length=50), nullable=True),
        sa.Column("trading_style", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("cash_balance", sa.Float(), nullable=True),
        sa.Column("invested_amount", sa.Float(), nullable=True),
        sa.Column("total_return", sa.Float(), nullable=True),
        sa.Column("total_return_percentage", sa.Float(), nullable=True),
        sa.Column("auto_rebalance", sa.Boolean(), nullable=True),
        sa.Column("rebalance_threshold", sa.Float(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_id"), "portfolios", ["id"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("average_cost", sa.Float(), nullable=False),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.Column("market_value", sa.Float(), nullable=False),
        sa.Column("unrealized_gain_loss", sa.Float(), nullable=True),
        sa.Column("unrealized_gain_loss_percentage", sa.Float(), nullable=True),
        sa.Column("target_allocation_percentage", sa.Float(), nullable=True),
        sa.Column("current_allocation_percentage", sa.Float(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holdings_id"), "holdings", ["id"], unique=False)
    op.create_index(op.f("ix_holdings_symbol"), "holdings", ["symbol"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column(
            "trade_type", sa.Enum("BUY", "SELL", name="tradetype"), nullable=False
        ),
        sa.Column("side", sa.Enum("BUY", "SELL", name="tradetype"), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum(
                "MARKET", "LIMIT", "STOP", "STOP_LOSS", "STOP_LIMIT", name="ordertype"
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("filled_quantity", sa.Float(), nullable=True),
        sa.Column("filled_price", sa.Float(), nullable=True),
        sa.Column("stop_price", sa.Float(), nullable=True),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "FILLED",
                "PARTIALLY_FILLED",
                "CANCELLED",
                "REJECTED",
                name="tradestatus",
            ),
            nullable=True,
        ),
        sa.Column("broker_order_id", sa.String(length=255), nullable=True),
        sa.Column("external_order_id", sa.String(length=255), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("commission", sa.Float(), nullable=True),
        sa.Column("fees", sa.Float(), nullable=True),
        sa.Column("strategy", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_paper_trade", sa.Boolean(), nullable=True),
        sa.Column("parent_order_id", sa.String(length=36), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trades_broker_order_id"), "trades", ["broker_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_trades_external_order_id"),
        "trades",
        ["external_order_id"],
        unique=False,
    )
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    op.create_table(
        "trade_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("executed_quantity", sa.Float(), nullable=False),
        sa.Column("executed_price", sa.Float(), nullable=False),
        sa.Column("execution_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_id", sa.String(length=255), nullable=True),
        sa.Column("broker_commission", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_executions_id"), "trade_executions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_executions_id"), table_name="trade_executions")
    op.drop_table("trade_executions")
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades")
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_external_order_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_broker_order_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_holdings_symbol"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_id"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_portfolios_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_technical_indicators_symbol"), table_name="technical_indicators"
    )
    op.drop_index(op.f("ix_technical_indicators_id"), table_name="technical_indicators")
    op.drop_index("idx_symbol_indicator_timestamp", table_name="technical_indicators")
    op.drop_table("technical_indicators")
    op.drop_index(op.f("ix_market_sentiment_symbol"), table_name="market_sentiment")
    op.drop_index(op.f("ix_market_sentiment_id"), table_name="market_sentiment")
    op.drop_index("idx_symbol_timestamp_sentiment", table_name="market_sentiment")
    op.drop_table("market_sentiment")
    op.drop_index(op.f("ix_market_data_symbol"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_id"), table_name="market_data")
    op.drop_index("idx_symbol_timestamp", table_name="market_data")
    op.drop_index("idx_symbol_timeframe_timestamp", table_name="market_data")
    op.drop_table("market_data")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
