"""add_education_tables

Revision ID: fe05daf7e673
Revises: add_webauthn_2025_12_06
Create Date: 2025-12-06 07:44:52.662755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe05daf7e673'
down_revision: Union[str, Sequence[str], None] = 'add_webauthn_2025_12_06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('MODULE', 'QUIZ', 'ARTICLE', 'INTERACTIVE', 'VIDEO', name='contenttype'), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='contentlevel'), nullable=False),
    sa.Column('completion_requirement', sa.Enum('NONE', 'QUIZ', 'TIME', 'INTERACTION', name='completionrequirement'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('content_path', sa.String(length=255), nullable=True),
    sa.Column('associated_quiz_id', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associated_quiz_id'], ['educational_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_content_id'), 'educational_content', ['id'], unique=False)
    op.create_index(op.f('ix_educational_content_slug'), 'educational_content', ['slug'], unique=True)
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=True)
    op.create_table('content_prerequisites',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['educational_content.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['educational_content.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'prerequisite_id')
    )
    op.create_table('learning_path_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['educational_content.id'], ),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_path_id', 'content_id', name='uq_learning_path_content')
    )
    op.create_index(op.f('ix_learning_path_items_id'), 'learning_path_items', ['id'], unique=False)
    op.create_table('trading_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('requires_guardian_approval', sa.Boolean(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('required_learning_path_id', sa.Integer(), nullable=True),
    sa.Column('required_content_id', sa.Integer(), nullable=True),
    sa.Column('required_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['required_content_id'], ['educational_content.id'], ),
    sa.ForeignKeyConstraint(['required_learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_permissions_id'), 'trading_permissions', ['id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['educational_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content_progress')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['trading_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    # ### end Alembic commands ###
    # Note: Schema changes to existing tables (trade_executions, trades, users) removed due to SQLite limitations


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Schema changes to existing tables (trade_executions, trades, users) removed due to SQLite limitations
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_trading_permissions_id'), table_name='trading_permissions')
    op.drop_table('trading_permissions')
    op.drop_index(op.f('ix_learning_path_items_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_table('content_prerequisites')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_educational_content_slug'), table_name='educational_content')
    op.drop_index(op.f('ix_educational_content_id'), table_name='educational_content')
    op.drop_table('educational_content')
    # ### end Alembic commands ###
