"""
Elson Financial AI - API Schemas

Pydantic models for request/response validation across all API endpoints.
"""

# Accounting Workflow Schemas
from .accounting_schemas import AccountBalance
from .accounting_schemas import (
    AccountTypeEnum as AcctAccountTypeEnum,  # Enums (note: AccountTypeEnum is redefined for accounting); Schema 1: Ledger Import; Schema 2: Monthly Close; Schema 3: Cash Flow Forecast; Schema 4: Budget Plan; Schema 5: Business KPIs; GnuCash Import
)
from .accounting_schemas import (
    BudgetCategoryEnum,
    BudgetLineItem,
    BudgetPlan,
    BudgetSummary,
    BusinessKPIs,
    CashFlowForecast,
    CashFlowItem,
    CashFlowPeriod,
    CategorySuggestion,
    CloseCheckItem,
    FrequencyEnum,
    GnuCashAccount,
    GnuCashImportResult,
    KPIMetric,
    LedgerImport,
    MonthlyCloseChecklist,
    Transaction,
    TransactionStatusEnum,
)

# Insurance Workflow Schemas
from .insurance_schemas import (  # Enums; Schema 1: Policy Comparison; Schema 2: Suitability Assessment; Schema 3: Needs Analysis; Schema 4: Premium Illustration; Schema 5: Claims Scenario
    ClaimsScenarioChecklist,
    ClaimStep,
    ClientInsuranceProfile,
    CoverageGap,
    IllustrationYear,
    IncomeReplacementCalculation,
    InsurancePurposeEnum,
    InsuranceTypeEnum,
    NeedsAnalysis,
    PolicyComparison,
    PolicyFeature,
    PremiumComparison,
    PremiumIllustrationSummary,
    RiskClassEnum,
    SuitabilityAssessment,
    SuitabilityFactor,
    SuitabilityStatusEnum,
)

# Structured Output Schemas (7 core)
from .output_schemas import (  # Enums; Schema 1: Financial Plan; Schema 2: Portfolio Policy Statement; Schema 3: Trade Plan; Schema 4: Tax Scenario Summary; Schema 5: Compliance Checklist; Schema 6: Market Data Request; Schema 7: Fundamental Analysis Report
    AccountTypeEnum,
    AssetAllocation,
    AssetClassEnum,
    CashFlowProjection,
    ComplianceCheckItem,
    ComplianceChecklist,
    ComplianceStatusEnum,
    DebtItem,
    FinancialGoal,
    FinancialHealthIndicator,
    FinancialPlan,
    FundamentalAnalysisReport,
    InsuranceCoverage,
    InvestmentRestriction,
    MarketDataRequest,
    PortfolioPolicyStatement,
    RiskToleranceEnum,
    TaxBracketImpact,
    TaxFilingStatusEnum,
    TaxScenario,
    TaxScenarioSummary,
    TimeHorizonEnum,
    TradeOrder,
    TradePlan,
    ValuationAssessment,
)

# Tool Schemas (OpenBB, FinanceToolkit)
from .tool_schemas import (  # Enums; OpenBB schemas; FinanceToolkit schemas; Tool call wrappers
    BalanceSheet,
    CashFlowStatement,
    FinancialStatementsRequest,
    FinancialStatementsResponse,
    FundamentalsRequest,
    FundamentalsResponse,
    IncomeStatement,
    MacroDataPoint,
    MacroRequest,
    MacroResponse,
    MacroSeriesEnum,
    NewsItem,
    NewsRequest,
    NewsResponse,
    OHLCVBar,
    OHLCVRequest,
    OHLCVResponse,
    QuoteRequest,
    QuoteResponse,
    RatioCategory,
    RatioCategoryEnum,
    RatioCategoryRequest,
    RatioCategoryResponse,
    RatioCompareRequest,
    RatioCompareResponse,
    RatioSummaryRequest,
    RatioSummaryResponse,
    RatioValue,
    TimeframeEnum,
    ToolCall,
    ToolResponse,
)

# Wealth Advisory Schemas
from .wealth_advisory import (  # Enums; Base models; Request models; Response models
    ActionItem,
    AdvisoryMode,
    Citation,
    CredentialInfoRequest,
    CredentialInfoResponse,
    CredentialType,
    EstatePlanningRequest,
    EstatePlanningResponse,
    FinancialLiteracyRequest,
    FinancialLiteracyResponse,
    KnowledgeBaseStatsResponse,
    ProfessionalRecommendation,
    ProfessionalRoleType,
    RoleInfoRequest,
    RoleInfoResponse,
    SuccessionPlanningRequest,
    SuccessionPlanningResponse,
    TeamCoordinationRequest,
    TeamCoordinationResponse,
    WealthAdvisoryRequest,
    WealthAdvisoryResponse,
    WealthTier,
)

__all__ = [
    # Tool Schemas
    "TimeframeEnum",
    "RatioCategoryEnum",
    "MacroSeriesEnum",
    "QuoteRequest",
    "QuoteResponse",
    "OHLCVRequest",
    "OHLCVBar",
    "OHLCVResponse",
    "FundamentalsRequest",
    "FundamentalsResponse",
    "NewsRequest",
    "NewsItem",
    "NewsResponse",
    "MacroRequest",
    "MacroDataPoint",
    "MacroResponse",
    "FinancialStatementsRequest",
    "IncomeStatement",
    "BalanceSheet",
    "CashFlowStatement",
    "FinancialStatementsResponse",
    "RatioSummaryRequest",
    "RatioValue",
    "RatioCategory",
    "RatioSummaryResponse",
    "RatioCategoryRequest",
    "RatioCategoryResponse",
    "RatioCompareRequest",
    "RatioCompareResponse",
    "ToolCall",
    "ToolResponse",
    # Structured Output Schemas
    "RiskToleranceEnum",
    "TimeHorizonEnum",
    "TaxFilingStatusEnum",
    "AccountTypeEnum",
    "AssetClassEnum",
    "ComplianceStatusEnum",
    "FinancialGoal",
    "CashFlowProjection",
    "DebtItem",
    "InsuranceCoverage",
    "FinancialPlan",
    "AssetAllocation",
    "InvestmentRestriction",
    "PortfolioPolicyStatement",
    "TradeOrder",
    "TradePlan",
    "TaxBracketImpact",
    "TaxScenario",
    "TaxScenarioSummary",
    "ComplianceCheckItem",
    "ComplianceChecklist",
    "MarketDataRequest",
    "ValuationAssessment",
    "FinancialHealthIndicator",
    "FundamentalAnalysisReport",
    # Insurance Workflow Schemas
    "InsuranceTypeEnum",
    "InsurancePurposeEnum",
    "RiskClassEnum",
    "SuitabilityStatusEnum",
    "PolicyFeature",
    "PremiumComparison",
    "PolicyComparison",
    "ClientInsuranceProfile",
    "SuitabilityFactor",
    "SuitabilityAssessment",
    "CoverageGap",
    "IncomeReplacementCalculation",
    "NeedsAnalysis",
    "IllustrationYear",
    "PremiumIllustrationSummary",
    "ClaimStep",
    "ClaimsScenarioChecklist",
    # Accounting Workflow Schemas
    "AcctAccountTypeEnum",
    "TransactionStatusEnum",
    "BudgetCategoryEnum",
    "FrequencyEnum",
    "Transaction",
    "CategorySuggestion",
    "LedgerImport",
    "CloseCheckItem",
    "AccountBalance",
    "MonthlyCloseChecklist",
    "CashFlowItem",
    "CashFlowPeriod",
    "CashFlowForecast",
    "BudgetLineItem",
    "BudgetSummary",
    "BudgetPlan",
    "KPIMetric",
    "BusinessKPIs",
    "GnuCashAccount",
    "GnuCashImportResult",
    # Wealth Advisory
    "AdvisoryMode",
    "WealthTier",
    "CredentialType",
    "ProfessionalRoleType",
    "Citation",
    "ProfessionalRecommendation",
    "ActionItem",
    "WealthAdvisoryRequest",
    "EstatePlanningRequest",
    "SuccessionPlanningRequest",
    "TeamCoordinationRequest",
    "FinancialLiteracyRequest",
    "CredentialInfoRequest",
    "RoleInfoRequest",
    "WealthAdvisoryResponse",
    "EstatePlanningResponse",
    "SuccessionPlanningResponse",
    "TeamCoordinationResponse",
    "FinancialLiteracyResponse",
    "CredentialInfoResponse",
    "RoleInfoResponse",
    "KnowledgeBaseStatsResponse",
]
