#!/usr/bin/env python3
"""
Expanded Quiz Templates for Elson Financial AI

Additional questions to expand the evaluation benchmark to 1000 questions.
"""

EXPANDED_QUIZZES = {
    "budgeting": {
        "weight": 0.08,
        "questions": [
            # More Easy questions
            {"subdomain": "basics", "difficulty": "easy", "question_type": "factual",
             "question": "What is zero-based budgeting?",
             "expected_elements": ["every dollar assigned", "income minus expenses equals zero", "intentional"],
             "prohibited_elements": ["guaranteed", "only way"]},
            {"subdomain": "basics", "difficulty": "easy", "question_type": "factual",
             "question": "What is the envelope budgeting method?",
             "expected_elements": ["cash", "categories", "physical or digital envelopes"],
             "prohibited_elements": ["best method", "only method"]},
            {"subdomain": "basics", "difficulty": "easy", "question_type": "factual",
             "question": "What are fixed expenses versus variable expenses?",
             "expected_elements": ["consistent amount", "fluctuate", "examples"],
             "prohibited_elements": ["always", "guaranteed"]},
            {"subdomain": "tracking", "difficulty": "easy", "question_type": "explanation",
             "question": "Why is tracking expenses important for budgeting?",
             "expected_elements": ["awareness", "patterns", "adjustments", "accountability"],
             "prohibited_elements": ["guaranteed success", "only way"]},
            # Medium
            {"subdomain": "strategies", "difficulty": "medium", "question_type": "comparison",
             "question": "Compare the pay yourself first strategy to traditional budgeting.",
             "expected_elements": ["savings priority", "automation", "behavior change"],
             "prohibited_elements": ["always better", "guaranteed"]},
            {"subdomain": "strategies", "difficulty": "medium", "question_type": "scenario",
             "question": "How should someone budget with irregular income?",
             "expected_elements": ["baseline expenses", "buffer", "prioritize", "variable income"],
             "prohibited_elements": ["simple", "easy"]},
            {"subdomain": "psychology", "difficulty": "medium", "question_type": "explanation",
             "question": "How does lifestyle creep affect financial goals?",
             "expected_elements": ["income increase", "spending increase", "savings rate"],
             "prohibited_elements": ["always avoid", "never spend more"]},
            # Hard
            {"subdomain": "advanced", "difficulty": "hard", "question_type": "calculation",
             "question": "Calculate the opportunity cost of a $500/month car payment over 30 years at 7% return.",
             "expected_elements": ["future value", "compound interest", "opportunity cost"],
             "prohibited_elements": ["exact prediction", "guaranteed return"]},
            {"subdomain": "advanced", "difficulty": "hard", "question_type": "scenario",
             "question": "Design a budget for a household with $150,000 income, $3,000 mortgage, and two children.",
             "expected_elements": ["tax considerations", "childcare", "savings", "emergency fund"],
             "prohibited_elements": ["one size fits all", "exact percentages required"]},
        ]
    },

    "credit_management": {
        "weight": 0.06,
        "questions": [
            {"subdomain": "credit_score", "difficulty": "easy", "question_type": "factual",
             "question": "What are the five factors that determine a FICO credit score?",
             "expected_elements": ["payment history", "amounts owed", "length of history", "credit mix", "new credit"],
             "prohibited_elements": ["exact weights guaranteed", "only factors"]},
            {"subdomain": "credit_score", "difficulty": "easy", "question_type": "factual",
             "question": "What is credit utilization and what ratio is considered good?",
             "expected_elements": ["balance to limit", "30%", "revolving credit"],
             "prohibited_elements": ["exact threshold", "always"]},
            {"subdomain": "credit_reports", "difficulty": "easy", "question_type": "factual",
             "question": "What are the three major credit bureaus?",
             "expected_elements": ["Equifax", "Experian", "TransUnion"],
             "prohibited_elements": ["all identical", "only ones"]},
            {"subdomain": "credit_building", "difficulty": "medium", "question_type": "procedural",
             "question": "How can someone with no credit history start building credit?",
             "expected_elements": ["secured card", "authorized user", "credit builder loan"],
             "prohibited_elements": ["instant", "guaranteed approval"]},
            {"subdomain": "credit_repair", "difficulty": "medium", "question_type": "explanation",
             "question": "What is the process for disputing errors on a credit report?",
             "expected_elements": ["written dispute", "investigation", "30 days", "documentation"],
             "prohibited_elements": ["guaranteed removal", "instant fix"]},
            {"subdomain": "credit_cards", "difficulty": "medium", "question_type": "comparison",
             "question": "Compare balance transfer cards to debt consolidation loans.",
             "expected_elements": ["intro APR", "fees", "fixed payment", "credit impact"],
             "prohibited_elements": ["always better", "guaranteed savings"]},
            {"subdomain": "fraud", "difficulty": "hard", "question_type": "procedural",
             "question": "What steps should someone take if they're a victim of identity theft?",
             "expected_elements": ["freeze", "fraud alert", "FTC report", "dispute"],
             "prohibited_elements": ["simple", "quick fix"]},
            {"subdomain": "advanced", "difficulty": "hard", "question_type": "scenario",
             "question": "Analyze the impact of closing old credit cards on credit score and credit history.",
             "expected_elements": ["utilization", "average age", "credit mix", "timing"],
             "prohibited_elements": ["never close", "always close"]},
        ]
    },

    "investment_basics": {
        "weight": 0.08,
        "questions": [
            {"subdomain": "asset_classes", "difficulty": "easy", "question_type": "factual",
             "question": "What are the main asset classes for investing?",
             "expected_elements": ["stocks", "bonds", "cash", "real estate", "commodities"],
             "prohibited_elements": ["best", "guaranteed"]},
            {"subdomain": "asset_classes", "difficulty": "easy", "question_type": "comparison",
             "question": "What is the difference between stocks and bonds?",
             "expected_elements": ["ownership", "debt", "risk", "return potential"],
             "prohibited_elements": ["always", "guaranteed"]},
            {"subdomain": "diversification", "difficulty": "easy", "question_type": "factual",
             "question": "What is diversification and why is it important?",
             "expected_elements": ["spread risk", "different investments", "not all eggs"],
             "prohibited_elements": ["eliminates risk", "guaranteed"]},
            {"subdomain": "funds", "difficulty": "easy", "question_type": "comparison",
             "question": "What is the difference between mutual funds and ETFs?",
             "expected_elements": ["trading", "expense ratios", "minimum investment", "tax efficiency"],
             "prohibited_elements": ["always better", "guaranteed"]},
            {"subdomain": "risk", "difficulty": "medium", "question_type": "explanation",
             "question": "What is the relationship between risk and return in investing?",
             "expected_elements": ["higher risk higher potential return", "no guarantee", "time horizon"],
             "prohibited_elements": ["guaranteed", "always"]},
            {"subdomain": "strategies", "difficulty": "medium", "question_type": "explanation",
             "question": "What is dollar cost averaging and when is it useful?",
             "expected_elements": ["regular intervals", "average price", "reduces timing risk"],
             "prohibited_elements": ["guaranteed profit", "always works"]},
            {"subdomain": "strategies", "difficulty": "medium", "question_type": "comparison",
             "question": "Compare value investing to growth investing approaches.",
             "expected_elements": ["undervalued", "high growth", "P/E ratios", "different goals"],
             "prohibited_elements": ["always better", "guaranteed returns"]},
            {"subdomain": "indices", "difficulty": "medium", "question_type": "factual",
             "question": "What is the S&P 500 and why is it used as a benchmark?",
             "expected_elements": ["500 companies", "market cap weighted", "broad market"],
             "prohibited_elements": ["only index", "guaranteed"]},
            {"subdomain": "analysis", "difficulty": "hard", "question_type": "explanation",
             "question": "Explain the efficient market hypothesis and its implications for investors.",
             "expected_elements": ["information reflected", "weak/semi-strong/strong", "passive investing"],
             "prohibited_elements": ["proven", "always true"]},
            {"subdomain": "behavioral", "difficulty": "hard", "question_type": "explanation",
             "question": "How does loss aversion affect investment decisions?",
             "expected_elements": ["losses feel worse", "selling winners", "holding losers"],
             "prohibited_elements": ["easy to overcome", "doesn't affect"]},
            {"subdomain": "advanced", "difficulty": "extremely_complex", "question_type": "calculation",
             "question": "Calculate the Sharpe ratio for a portfolio with 10% return, 2% risk-free rate, and 15% standard deviation.",
             "expected_elements": ["excess return", "risk-adjusted", "standard deviation"],
             "prohibited_elements": ["guaranteed", "only metric"]},
        ]
    },

    "real_estate": {
        "weight": 0.06,
        "questions": [
            {"subdomain": "buying", "difficulty": "easy", "question_type": "factual",
             "question": "What is a down payment and how much is typically required?",
             "expected_elements": ["upfront payment", "20% conventional", "PMI", "varies by loan type"],
             "prohibited_elements": ["always 20%", "exact requirement"]},
            {"subdomain": "buying", "difficulty": "easy", "question_type": "factual",
             "question": "What costs are included in closing costs?",
             "expected_elements": ["origination fees", "title insurance", "appraisal", "escrow"],
             "prohibited_elements": ["exact amount", "always same"]},
            {"subdomain": "mortgages", "difficulty": "easy", "question_type": "comparison",
             "question": "What is the difference between fixed-rate and adjustable-rate mortgages?",
             "expected_elements": ["rate changes", "initial rate", "risk", "payment stability"],
             "prohibited_elements": ["always better", "guaranteed"]},
            {"subdomain": "mortgages", "difficulty": "medium", "question_type": "calculation",
             "question": "How is the debt-to-income ratio calculated for mortgage qualification?",
             "expected_elements": ["monthly debt", "gross income", "front-end", "back-end"],
             "prohibited_elements": ["exact threshold", "guaranteed approval"]},
            {"subdomain": "investing", "difficulty": "medium", "question_type": "explanation",
             "question": "What is a 1031 exchange and how does it work?",
             "expected_elements": ["tax-deferred", "like-kind", "timelines", "qualified intermediary"],
             "prohibited_elements": ["tax free", "no requirements"]},
            {"subdomain": "investing", "difficulty": "medium", "question_type": "calculation",
             "question": "How do you calculate cap rate for an investment property?",
             "expected_elements": ["NOI", "purchase price", "percentage", "comparison tool"],
             "prohibited_elements": ["only metric", "guaranteed return"]},
            {"subdomain": "investing", "difficulty": "hard", "question_type": "scenario",
             "question": "Compare the returns of a rental property to a REIT investment with $100,000.",
             "expected_elements": ["cash flow", "appreciation", "liquidity", "management", "leverage"],
             "prohibited_elements": ["always better", "guaranteed"]},
            {"subdomain": "tax", "difficulty": "hard", "question_type": "explanation",
             "question": "Explain depreciation for rental property and depreciation recapture.",
             "expected_elements": ["27.5 years", "taxable income reduction", "recapture on sale", "25% rate"],
             "prohibited_elements": ["free deduction", "no consequences"]},
            {"subdomain": "advanced", "difficulty": "extremely_complex", "question_type": "scenario",
             "question": "Analyze a Delaware Statutory Trust (DST) for a 1031 exchange with $500,000.",
             "expected_elements": ["passive investment", "identified property", "risks", "fees"],
             "prohibited_elements": ["guaranteed", "simple"]},
        ]
    },

    "social_security": {
        "weight": 0.05,
        "questions": [
            {"subdomain": "eligibility", "difficulty": "easy", "question_type": "factual",
             "question": "How many work credits are needed to qualify for Social Security retirement benefits?",
             "expected_elements": ["40 credits", "10 years", "work credits"],
             "prohibited_elements": ["exact benefit", "guaranteed amount"]},
            {"subdomain": "claiming", "difficulty": "easy", "question_type": "factual",
             "question": "What is the earliest age to claim Social Security retirement benefits?",
             "expected_elements": ["62", "reduced benefits", "permanent reduction"],
             "prohibited_elements": ["best age", "always claim"]},
            {"subdomain": "calculation", "difficulty": "medium", "question_type": "explanation",
             "question": "How is the Social Security retirement benefit calculated?",
             "expected_elements": ["AIME", "PIA", "35 years", "bend points"],
             "prohibited_elements": ["exact amount", "guaranteed"]},
            {"subdomain": "strategy", "difficulty": "medium", "question_type": "comparison",
             "question": "Compare claiming Social Security at 62 versus 67 versus 70.",
             "expected_elements": ["reduction", "delay credits", "breakeven", "longevity"],
             "prohibited_elements": ["always best", "guaranteed"]},
            {"subdomain": "spousal", "difficulty": "medium", "question_type": "explanation",
             "question": "How do spousal Social Security benefits work?",
             "expected_elements": ["50% of spouse", "own record", "coordination"],
             "prohibited_elements": ["automatic", "always 50%"]},
            {"subdomain": "taxation", "difficulty": "hard", "question_type": "calculation",
             "question": "How is Social Security taxed at different income levels?",
             "expected_elements": ["provisional income", "50%/85%", "thresholds"],
             "prohibited_elements": ["never taxed", "always taxed"]},
            {"subdomain": "strategy", "difficulty": "hard", "question_type": "scenario",
             "question": "Design a Social Security claiming strategy for a married couple ages 62 and 65.",
             "expected_elements": ["survivor benefits", "coordination", "income needs"],
             "prohibited_elements": ["simple answer", "always"]},
            {"subdomain": "advanced", "difficulty": "extremely_complex", "question_type": "calculation",
             "question": "Calculate the breakeven age for delaying Social Security from 62 to 70.",
             "expected_elements": ["cumulative benefits", "inflation", "investment return"],
             "prohibited_elements": ["guaranteed optimal", "simple"]},
        ]
    },

    "business_finance": {
        "weight": 0.05,
        "questions": [
            {"subdomain": "entity_types", "difficulty": "easy", "question_type": "comparison",
             "question": "What is the difference between an LLC and an S-Corp?",
             "expected_elements": ["liability protection", "taxation", "self-employment tax"],
             "prohibited_elements": ["always better", "simple choice"]},
            {"subdomain": "entity_types", "difficulty": "easy", "question_type": "factual",
             "question": "What is a sole proprietorship and what are its tax implications?",
             "expected_elements": ["not separate entity", "Schedule C", "self-employment tax"],
             "prohibited_elements": ["no liability", "always avoid"]},
            {"subdomain": "taxation", "difficulty": "medium", "question_type": "explanation",
             "question": "How does S-Corp election affect self-employment tax?",
             "expected_elements": ["reasonable salary", "distributions", "payroll tax savings"],
             "prohibited_elements": ["avoid all tax", "simple"]},
            {"subdomain": "retirement", "difficulty": "medium", "question_type": "comparison",
             "question": "Compare SEP-IRA, SIMPLE IRA, and Solo 401(k) for self-employed individuals.",
             "expected_elements": ["contribution limits", "employees", "complexity"],
             "prohibited_elements": ["always best", "guaranteed"]},
            {"subdomain": "deductions", "difficulty": "medium", "question_type": "factual",
             "question": "What home office deduction methods are available for self-employed individuals?",
             "expected_elements": ["simplified method", "regular method", "exclusive use"],
             "prohibited_elements": ["automatic", "no restrictions"]},
            {"subdomain": "strategy", "difficulty": "hard", "question_type": "scenario",
             "question": "When should a business owner consider converting from LLC to S-Corp?",
             "expected_elements": ["profit threshold", "reasonable salary", "complexity cost"],
             "prohibited_elements": ["always convert", "guaranteed savings"]},
            {"subdomain": "exit", "difficulty": "hard", "question_type": "explanation",
             "question": "What are the tax implications of selling a business structured as a C-Corp?",
             "expected_elements": ["double taxation", "asset vs stock sale", "QSBS"],
             "prohibited_elements": ["simple", "no tax"]},
            {"subdomain": "advanced", "difficulty": "extremely_complex", "question_type": "calculation",
             "question": "Analyze the tax efficiency of a Cash Balance Plan combined with 401(k) for a high-income professional.",
             "expected_elements": ["defined benefit", "contribution limits", "actuarial"],
             "prohibited_elements": ["simple", "guaranteed"]},
        ]
    },

    "healthcare_finance": {
        "weight": 0.04,
        "questions": [
            {"subdomain": "hsa", "difficulty": "easy", "question_type": "factual",
             "question": "What is an HSA and what are the eligibility requirements?",
             "expected_elements": ["Health Savings Account", "HDHP", "triple tax advantage"],
             "prohibited_elements": ["anyone can have", "guaranteed"]},
            {"subdomain": "hsa", "difficulty": "medium", "question_type": "explanation",
             "question": "How can an HSA be used as a retirement savings vehicle?",
             "expected_elements": ["invest", "carry over", "65 withdrawal", "tax-free medical"],
             "prohibited_elements": ["best retirement account", "guaranteed"]},
            {"subdomain": "fsa", "difficulty": "easy", "question_type": "comparison",
             "question": "What is the difference between an HSA and an FSA?",
             "expected_elements": ["portability", "rollover", "eligibility", "contribution source"],
             "prohibited_elements": ["always better", "identical"]},
            {"subdomain": "medicare", "difficulty": "medium", "question_type": "explanation",
             "question": "What are the different parts of Medicare (A, B, C, D)?",
             "expected_elements": ["hospital", "medical", "Medicare Advantage", "prescription"],
             "prohibited_elements": ["free", "no cost"]},
            {"subdomain": "medicare", "difficulty": "hard", "question_type": "calculation",
             "question": "How are IRMAA surcharges calculated for Medicare Parts B and D?",
             "expected_elements": ["MAGI", "income thresholds", "surcharge amounts"],
             "prohibited_elements": ["avoid", "workaround"]},
            {"subdomain": "planning", "difficulty": "hard", "question_type": "scenario",
             "question": "Plan healthcare coverage for early retirement between ages 55-65.",
             "expected_elements": ["COBRA", "ACA marketplace", "HSA", "cost projection"],
             "prohibited_elements": ["simple", "cheap"]},
        ]
    },

    "behavioral_finance": {
        "weight": 0.03,
        "questions": [
            {"subdomain": "biases", "difficulty": "easy", "question_type": "factual",
             "question": "What is confirmation bias in investing?",
             "expected_elements": ["seeking confirming information", "ignoring contrary evidence"],
             "prohibited_elements": ["easy to avoid", "doesn't affect professionals"]},
            {"subdomain": "biases", "difficulty": "medium", "question_type": "explanation",
             "question": "How does anchoring bias affect investment decisions?",
             "expected_elements": ["reference point", "purchase price", "slow to adjust"],
             "prohibited_elements": ["easy fix", "doesn't exist"]},
            {"subdomain": "biases", "difficulty": "medium", "question_type": "scenario",
             "question": "Identify the herd mentality bias in the 2021 meme stock phenomenon.",
             "expected_elements": ["following crowd", "FOMO", "social proof", "risk"],
             "prohibited_elements": ["always wrong", "always right"]},
            {"subdomain": "strategies", "difficulty": "hard", "question_type": "explanation",
             "question": "How can systematic investment rules help overcome behavioral biases?",
             "expected_elements": ["automation", "predetermined rules", "emotion removal"],
             "prohibited_elements": ["eliminate all bias", "guaranteed success"]},
        ]
    },

    "international_finance": {
        "weight": 0.03,
        "questions": [
            {"subdomain": "taxation", "difficulty": "medium", "question_type": "factual",
             "question": "What is FBAR and who must file it?",
             "expected_elements": ["foreign bank accounts", "$10,000", "FinCEN 114"],
             "prohibited_elements": ["optional", "ignore"],
             "compliance_sensitive": True},
            {"subdomain": "taxation", "difficulty": "medium", "question_type": "explanation",
             "question": "How does the Foreign Earned Income Exclusion work?",
             "expected_elements": ["bona fide residence", "physical presence", "exclusion amount"],
             "prohibited_elements": ["avoid all tax", "automatic"]},
            {"subdomain": "investing", "difficulty": "hard", "question_type": "explanation",
             "question": "What are the tax implications of investing in PFICs (Passive Foreign Investment Companies)?",
             "expected_elements": ["excess distribution", "QEF election", "mark-to-market"],
             "prohibited_elements": ["simple", "no implications"],
             "compliance_sensitive": True},
            {"subdomain": "estate", "difficulty": "extremely_complex", "question_type": "scenario",
             "question": "Analyze estate planning for a US citizen with foreign assets and foreign beneficiaries.",
             "expected_elements": ["treaty", "foreign death tax credit", "Form 706"],
             "prohibited_elements": ["simple", "no complications"],
             "compliance_sensitive": True},
        ]
    },

    "charitable_giving": {
        "weight": 0.03,
        "questions": [
            {"subdomain": "basics", "difficulty": "easy", "question_type": "factual",
             "question": "What documentation is required for charitable deductions?",
             "expected_elements": ["written acknowledgment", "$250 threshold", "contemporaneous"],
             "prohibited_elements": ["no documentation", "any amount"]},
            {"subdomain": "strategies", "difficulty": "medium", "question_type": "explanation",
             "question": "How does donating appreciated stock benefit donors?",
             "expected_elements": ["avoid capital gains", "FMV deduction", "holding period"],
             "prohibited_elements": ["always best", "no limitations"]},
            {"subdomain": "daf", "difficulty": "medium", "question_type": "explanation",
             "question": "What is a Donor Advised Fund and how does it work?",
             "expected_elements": ["immediate deduction", "recommend grants", "investment growth"],
             "prohibited_elements": ["guaranteed", "no fees"]},
            {"subdomain": "advanced", "difficulty": "hard", "question_type": "comparison",
             "question": "Compare a Charitable Remainder Trust to a Charitable Lead Trust.",
             "expected_elements": ["income stream", "remainder", "estate tax", "income tax"],
             "prohibited_elements": ["simple", "always better"]},
            {"subdomain": "qcd", "difficulty": "hard", "question_type": "explanation",
             "question": "How do Qualified Charitable Distributions (QCDs) work and when are they beneficial?",
             "expected_elements": ["age 70.5", "direct transfer", "RMD", "AGI"],
             "prohibited_elements": ["anyone can use", "automatic"]},
        ]
    },

    "divorce_finance": {
        "weight": 0.02,
        "questions": [
            {"subdomain": "basics", "difficulty": "medium", "question_type": "explanation",
             "question": "What is a QDRO and when is it required?",
             "expected_elements": ["Qualified Domestic Relations Order", "retirement accounts", "tax-free transfer"],
             "prohibited_elements": ["simple", "automatic"]},
            {"subdomain": "taxation", "difficulty": "medium", "question_type": "factual",
             "question": "How is alimony treated for tax purposes post-2018?",
             "expected_elements": ["not deductible", "not income", "TCJA change"],
             "prohibited_elements": ["deductible", "pre-2018 rules"]},
            {"subdomain": "property", "difficulty": "hard", "question_type": "scenario",
             "question": "How should retirement account division consider after-tax values?",
             "expected_elements": ["pretax vs Roth", "tax basis", "equalization"],
             "prohibited_elements": ["simple split", "always equal"]},
        ]
    },

    "college_planning": {
        "weight": 0.04,
        "questions": [
            {"subdomain": "529_plans", "difficulty": "easy", "question_type": "factual",
             "question": "What is a 529 plan and what are its tax benefits?",
             "expected_elements": ["tax-free growth", "qualified expenses", "state deduction"],
             "prohibited_elements": ["guaranteed", "always best"]},
            {"subdomain": "529_plans", "difficulty": "medium", "question_type": "explanation",
             "question": "What happens to unused 529 funds?",
             "expected_elements": ["beneficiary change", "penalty", "Roth rollover"],
             "prohibited_elements": ["lost", "no options"]},
            {"subdomain": "financial_aid", "difficulty": "medium", "question_type": "explanation",
             "question": "How does FAFSA calculate Expected Family Contribution?",
             "expected_elements": ["income", "assets", "family size", "parent vs student"],
             "prohibited_elements": ["guaranteed aid", "simple formula"]},
            {"subdomain": "strategies", "difficulty": "hard", "question_type": "scenario",
             "question": "Design a college savings strategy for a high-income family with 10 years until college.",
             "expected_elements": ["529", "financial aid impact", "asset location"],
             "prohibited_elements": ["simple answer", "one strategy"]},
            {"subdomain": "advanced", "difficulty": "hard", "question_type": "comparison",
             "question": "Compare 529 plans to UTMA/UGMA accounts for college savings.",
             "expected_elements": ["control", "tax treatment", "financial aid", "flexibility"],
             "prohibited_elements": ["always 529", "always UTMA"]},
        ]
    },

    "elder_care": {
        "weight": 0.02,
        "questions": [
            {"subdomain": "medicaid", "difficulty": "medium", "question_type": "explanation",
             "question": "What is the Medicaid look-back period for long-term care?",
             "expected_elements": ["60 months", "asset transfers", "penalty period"],
             "prohibited_elements": ["hide assets", "easy workaround"],
             "compliance_sensitive": True},
            {"subdomain": "planning", "difficulty": "hard", "question_type": "scenario",
             "question": "What planning strategies are available for long-term care costs?",
             "expected_elements": ["LTC insurance", "Medicaid planning", "asset protection trusts"],
             "prohibited_elements": ["hide assets", "fraudulent transfer"],
             "compliance_sensitive": True},
            {"subdomain": "legal", "difficulty": "medium", "question_type": "factual",
             "question": "What are the key documents needed for elder care planning?",
             "expected_elements": ["POA", "healthcare proxy", "living will", "HIPAA authorization"],
             "prohibited_elements": ["optional", "unnecessary"]},
        ]
    },
}


def get_expanded_quizzes():
    """Return the expanded quiz dictionary"""
    return EXPANDED_QUIZZES
